POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123",
  "role": "ADMIN"
}

### Create Product
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "iPhone 17",
  "description": "Apple smartphone",
  "price": 999.99,
  "stockQuantity": 10
}

### Get All Products
GET http://localhost:8080/products

### Get Product By Id
GET http://localhost:8080/products/1

### Change Price
PATCH http://localhost:8080/products/1
Content-Type: application/json

{
  "price": 1099.99,
  "stockQuantity": 15
}

### Delete Product
DELETE http://localhost:8080/products/1

### Testing Validation
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "iPhone 17",
  "description": "Apple smartphone",
  "price": 0,
  "stockQuantity": -1
}